# Generated by Django 4.2.11 on 2024-04-17 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(max_length=250)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2024, 4, 17, 19, 42, 53, 318885, tzinfo=datetime.timezone.utc))),
                ('published_date', models.DateTimeField(default=datetime.datetime(2024, 4, 17, 19, 42, 53, 318885, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
