# Generated by Django 4.2.11 on 2024-04-17 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_posts_author_alter_posts_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 21, 21, 7, 206737, tzinfo=datetime.timezone.utc)),
        ),
    ]
