# Generated by Django 4.2.11 on 2024-04-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_posts_image_alter_posts_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
