# Generated by Django 4.2.11 on 2024-04-17 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_posts_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
