# Generated by Django 4.2.11 on 2024-04-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_alter_contactform_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
