# Generated by Django 4.2.11 on 2024-04-25 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_alter_contactform_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
