# Generated by Django 4.2.11 on 2024-04-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_alter_comment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
